In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame([
    [165, 137, 472, 192],
    [101, 92, 250, 144],
    [29, 127, 201, 91]],
    columns=['R&D', 'Ops', 'Marketing', 'Profit']
)

In [8]:
df

   R&D  Ops  Marketing  Profit
0  165  137        472     192
1  101   92        250     144
2   29  127        201      91

In [10]:
df['f0(x)'] = df['Profit'].mean()
df

   R&D  Ops  Marketing  Profit       f0(x)
0  165  137        472     192  142.333333
1  101   92        250     144  142.333333
2   29  127        201      91  142.333333

In [11]:
df['r1'] =  df['Profit'] - df['f0(x)']
df

   R&D  Ops  Marketing  Profit       f0(x)         r1
0  165  137        472     192  142.333333  49.666667
1  101   92        250     144  142.333333   1.666667
2   29  127        201      91  142.333333 -51.333333